"""Added sessions and association table for correct answers

Revision ID: 22a5f888ce1
Revises: 4ceb7b28bb6
Create Date: 2015-12-05 22:45:06.890049

"""

# revision identifiers, used by Alembic.
revision = '22a5f888ce1'
down_revision = '4ceb7b28bb6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_start', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=False)
    op.create_table('right_answers',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('tag_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.ForeignKeyConstraint(['tag_name'], ['tags.name'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('right_answers')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_table('sessions')
    ### end Alembic commands ###
