"""added confirmation tokens

Revision ID: 488589ebf2d
Revises: None
Create Date: 2015-12-03 21:02:58.733884

"""

# revision identifiers, used by Alembic.
revision = '488589ebf2d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
