"""Added tags

Revision ID: 4ceb7b28bb6
Revises: 488589ebf2d
Create Date: 2015-12-05 14:18:36.104577

"""

# revision identifiers, used by Alembic.
revision = '4ceb7b28bb6'
down_revision = '488589ebf2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('definition', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    ### end Alembic commands ###
